name: RoyalDeath
main: org.royaldev.royaldeath.RoyalDeath
version: 0.0.1
author: jkcclemens
website: http://dev.royaldev.org/

commands:
  royaldeath:
    description: Reloads the plugin.
    usage: /<command>
    aliases: [rdeath]
