name: RoyalDeath
main: org.royaldev.royaldeath.RoyalDeath
version: ${pluginversion}
author: jkcclemens
website: http://dev.royaldev.org/
softdepend: [Multiverse-Core]

commands:
  royaldeath:
    description: Reloads the plugin.
    usage: /<command>
    aliases: [rdeath]
